### ISSUE TITLE
UI - Explore - "Load More" option is presented even when on filtered results fetches entries that dont match the filter.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#726]
gptscript version v0.0.0-dev+b77cd130

**Steps to reproduce the problem:**
1. Launch UI.
2. Make sure you have many assistants that can be listed. In my case there are 17 assistants.
3. Go to Explorer
4. There are 10 assistants that are listed as expected with "Load More" option.
5. Filter the result , so that you get a few entries ( < 10)
Notice that you have a "Load More" option which when used results in fetching 2 more entries which dont match the filter criteria.

This was after using "Load More" option  when filter was set for `owner` and `tag`:

<img width="1378" alt="Screenshot 2024-08-06 at 1 03 25 PM" src="https://github.com/user-attachments/assets/df1fdb5c-00c9-4aec-a697-3f786350f1a6">

**Comment by tylerslaton** [comment]
This should be fixed now.

**Comment by sangee2004** [comment]
This issue is still reproducible when testing with commit id - `3787f27c0b`

Search for `gcp` tag, even when there is 1 entry there is a `load more` option
![Image](https://github.com/user-attachments/assets/9a96f4ae-8089-4a74-b4c3-397a31b41a9f)

Using this `load more` option , results in returning entries that dont match the search criteria
![Image](https://github.com/user-attachments/assets/9b32f320-87ed-46a8-977c-35e728640185)

**Comment by tylerslaton** [comment]
Can you give this another look? Turns out the fix wasn't pushed yet.
