### ISSUE TITLE
UI - Explore - Filters and Search are applied to only the first 10 assistant entries.  

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#731]
Electron app build wit commit id- 4414471

**Steps to reproduce the problem:**
1. Have more than 10 assistant entries so that you have to use the "Load More" to see the full list in `Explore` view.
2. Try to use the filters or search (by agent name) to fetch assistants that are not in the first 10 assistant entries.
Search will not return any entries that match the search criteria but are not present in the current assistant list (10 entries).  

Using "Load More" results in this issue - https://github.com/gptscript-ai/gptscript/issues/726

Expected Behavior:
Search and Filters should work on the the entire list of assistants and be able to present up to 10 entries from the search results.

**Comment by tylerslaton** [comment]
@sangee2004 this should be fixed now.

**Comment by sangee2004** [comment]
Tested with latest commit id - `c5e7e29371`

This issue still exists

In my case i am testing for `sangeenewworkspace` which is not in the first 10 assistants.

I get an empty result:
![Image](https://github.com/user-attachments/assets/28bd3be1-3a35-499f-a83a-d219dbb91a1b)

When I do "load more", entries presented do not match the agent i am searching for:
![Image](https://github.com/user-attachments/assets/6f184b7e-f041-48ed-832c-d4cb2182f67e)

**Comment by tylerslaton** [comment]
@sangee2004 I just pushed a new fix for this. Can you check again?
