### ISSUE TITLE
UI - Dependencies lost in edit tool page.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#739]
Electron app with commit id `6e2f8ed`

**Steps to reproduce the problem:**
1. While creating a script ,add a tool with Instruction Type set to “code” and code set to type “python” . Have some python code and  dependencies set.
2. Edit this script and edit the tool.
3. Notice that the "Dependencies" field is empty.

If we quit the edit page and try to execute the script , it will complain about missing modules since there are no requirements set .

Note - This issue is also seen when you edit the script and quit ( dont have to go to edit tool page).

**Comment by tylerslaton** [comment]
This should be fixed now. Can you give it another look?

**Comment by sangee2004** [comment]
Tested with commit id - `c5e7e2937`

In edit mode , I am still not presented with the dependencies that i added.


![Image](https://github.com/user-attachments/assets/70cc9ce6-b224-4099-8d7b-47fad4e032a0)


But dependencies continue to be present in the script. Even after I visit the edit page and exit , I am able to successfully chat with the assistant and make successful tool calls.
